executor: "KubernetesExecutor"

images:
  airflow:
    repository: localhost:5000/airflow-custom
    tag: "1.1.0"
    pullPolicy: IfNotPresent
  pod_template:
    repository: localhost:5000/airflow-custom
    tag: "1.1.0"
    pullPolicy: IfNotPresent

config:
  logging:
    remote_logging: 'True'
    remote_base_log_folder: 's3://airflow-logs/'
    remote_log_conn_id: 'aws_default'
    encrypt_s3_logs: 'False'

extraEnv: |
  - name: AIRFLOW_CONN_AWS_DEFAULT
    valueFrom:
      secretKeyRef:
        name: airflow-s3-conn
        key: connection

dags:
  gitSync:
    enabled: false

logs:
  persistence:
    enabled: false